version: '3'
services:
  chamilo_database:
    image: mariadb
    container_name: chamilo_database
    networks:
      - chamilonet
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=chamilo
      - MYSQL_PASSWORD=chamilo
      - MYSQL_DATABASE=chamilo
    volumes:
      - chamilo_database:/var/lib/mysql

  chamilo:
    image: macielbombonato/docker-chamilo:latest
    container_name: chamilo
    ports:
      - "8080:80"
    networks:
      - chamilonet
    links:
      - chamilo_database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - chamilo_database
    ports:
      - 32500:80
    environment:
      - PMA_ARBITRARY=1

networks:
  chamilonet:
    driver: bridge

volumes:
  chamilo_database: